### ISSUE TITLE
Revisar sonidos para conservar solamente sonidos muy breves.

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/huayra-ritmos-data#1]
Como la aplicación presenta canales con steps muy numerosos, lo ideal es que los sonidos que les proponemos en la galería sean de muy poca duración, 1 segundo como máximo...

**Comment by hugoruscitti** [comment]
Ojo @DiegoAccorinti  que le cambié de nombre al repositorio recién, a causa del issue #2

**Comment by DiegoAccorinti** [comment]
ok @hugoruscitti   gracias!

**Comment by hugoruscitti** [comment]
Marco como cerrado, genial!
